apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  A10_ADDRESS: {{ .Values.a10.address | quote }}
  A10_AS: {{ .Values.a10.as | quote }}
  A10_PASSWORD: {{ .Values.a10.password | quote }}
  A10_REMOTE_AS: {{ .Values.a10.remoteAS | quote }}
  A10_USERNAME: {{ .Values.a10.username | quote }}
  NODES_LABEL_SELECTOR: {{ .Values.nodesLabelSelector | quote }}
  DEBUG: {{ .Values.debug | default "" | quote }}
